# Generated by Django 4.2.5 on 2023-10-10 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basemodel')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            bases=('core.basemodel',),
        ),
        migrations.CreateModel(
            name='EpisodeAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Generator',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basemodel')),
                ('name', models.CharField(max_length=100)),
                ('hostname', models.CharField(blank=True, max_length=150, null=True)),
                ('genDate', models.DateTimeField(blank=True, null=True)),
            ],
            bases=('core.basemodel',),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basemodel')),
                ('url', models.URLField()),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('link', models.URLField(blank=True, null=True)),
            ],
            bases=('core.basemodel',),
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basemodel')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
            bases=('core.basemodel',),
        ),
        migrations.CreateModel(
            name='PodcastAuthor',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basemodel')),
                ('name', models.CharField(max_length=30)),
            ],
            bases=('core.basemodel',),
        ),
        migrations.CreateModel(
            name='PodcastUrl',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basemodel')),
                ('url', models.URLField(unique=True)),
                ('title', models.CharField(max_length=150)),
                ('is_saved', models.BooleanField(default=False)),
            ],
            bases=('core.basemodel',),
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=50)),
                ('itunes_type', models.CharField(max_length=50)),
                ('copy_right', models.CharField(max_length=100)),
                ('explicit', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('pubDate', models.DateTimeField(blank=True, null=True)),
                ('last_build_date', models.DateTimeField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('itunes_subtitle', models.TextField(blank=True, null=True)),
                ('itunes_keywords', models.TextField(blank=True, null=True)),
                ('itunes_image', models.CharField(max_length=400)),
                ('category', models.ManyToManyField(to='podcast.category')),
                ('podcast_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcast.podcastauthor')),
                ('podcast_generator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='podcast.generator')),
                ('podcast_image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='podcast.image')),
                ('podcast_url', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='podcast.podcasturl')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('guid', models.CharField(max_length=50)),
                ('itunes_duration', models.CharField(max_length=50)),
                ('itunes_episode_type', models.CharField(max_length=50)),
                ('itunes_explicit', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField()),
                ('enclosure', models.CharField(blank=True, max_length=100, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('pubDate', models.DateTimeField(blank=True, null=True)),
                ('itunes_keywords', models.TextField(blank=True, null=True)),
                ('itunes_player', models.CharField(blank=True, max_length=100, null=True)),
                ('episode_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='podcast.episodeauthor')),
                ('episode_podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode', to='podcast.podcast')),
            ],
        ),
    ]
