# Generated by Django 4.2.7 on 2023-11-04 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0003_alter_episode_enclosure_alter_episode_guid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='itunes_episode_type',
            new_name='itunes_episodeType',
        ),
        migrations.RenameField(
            model_name='podcast',
            old_name='explicit',
            new_name='itunens_explicit',
        ),
        migrations.RenameField(
            model_name='podcast',
            old_name='last_build_date',
            new_name='lastBuildDate',
        ),
    ]
