# Generated by Django 4.0.6 on 2023-11-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0005_podcast_podcast_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodeauthor',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='podcastauthor',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
