# Generated by Django 4.2.7 on 2023-11-05 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0006_alter_episodeauthor_name_alter_owner_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='podcast',
            old_name='itunens_explicit',
            new_name='itunes_explicit',
        ),
    ]
