# Generated by Django 4.2.7 on 2023-11-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0007_rename_itunens_explicit_podcast_itunes_explicit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='itunes_image',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
