# Generated by Django 4.2.7 on 2023-11-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0008_alter_podcast_itunes_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='guid',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='episode',
            name='itunes_player',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
