# Generated by Django 4.0.6 on 2023-11-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0009_alter_episode_guid_alter_episode_itunes_player_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='link',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
