# Generated by Django 4.0.6 on 2023-11-06 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0010_alter_image_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='podcast_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='podcast.podcastauthor'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='podcast_image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='podcast.image'),
        ),
    ]
