version: "3.8"

services:
    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:3-alpine
        networks:
            - main
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq
            - rabbitmq_log:/var/log/rabbitmq
        restart: always
        ports:
            - 5672:5672
            - 15672:15672

    
    postgres:
        image: postgres:16.0
        environment:
            POSTGRES_DB: "rss_feed"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "MaA98218"
        ports:
            - 5432:5432
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - main

    redis:
        image: redis:alpine
        ports:
            - 6379:6379
        networks:
            - main

    django:
        build: .
        container_name: django
        volumes:
            - .:/code/
        ports: 
            - 8000:8000
        depends_on:
            - postgres
            - redis
        networks:
            - main
    celery:
        build: .
        command: celery -A rss_feed worker -l INFO -B
        volumes:
            - .:/code/
        depends_on:
            - django
            - redis
        networks:
            - main

    counsumers:
        container_name: consumers
        build: .
        command: python3 manage.py runconsumers
        volumes:
            - .:/code/
        networks:
            - main
        depends_on:
            - rabbitmq
            - django
        restart: always

    elasticsearch:
        image: elasticsearch:7.17.3
        container_name: elasticsearch
        mem_limit: 512m
        volumes:
            - elasticsearch_data:/usr/share/elasticsearch/data
        environment:
            discovery.type: single-node
            ES_JAVA_OPTS: -Xms512m -Xmx512m
            xpack.security.enabled: 'false'
        ports:
            - 9200:9200
        networks:
            - main
    kibana:
        image: kibana:7.17.3
        container_name: kibana
        ports:
            - 5601:5601
        depends_on:
            - elasticsearch
        networks:
            - main
        restart: always
        volumes:
            - kibana_data:/usr/share/kibana/data
networks:
    main:
volumes:
    pgdata:
    kibana_data:
    elasticsearch_data:
    rabbitmq_data:
    rabbitmq_log: