version: "3.8"

services:
    django:
        build: .
        container_name: django
        volumes:
            - .:/code/
        ports: 
            - 8000:8000
        depends_on:
            - postgres
            - redis
        networks:
            - main
    celery:
        build: .
        command: celery -A rss_feed worker -l INFO -B
        volumes:
            - .:/code/
        depends_on:
            - django
            - redis
        networks:
            - main
    postgres:
        image: postgres:16.0
        environment:
            POSTGRES_DB: "rss_feed"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "MaA98218"
        ports:
            - 5432:5432
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - main
    redis:
        image: "redis:alpine"
        ports:
            - 6379:6379
        networks:
            - main
networks:
    main:
volumes:
    pgdata: